const names = [
    ['Ezekiel', 'Huffman'],
    ['Jamal', 'Davenport'],
    ['Paula', 'Mckee'],
    ['Fernanda', 'Knight'],
    ['Elaina', 'Marks'],
    ['Corey', 'Sims'],
    ['Victor', 'Abbott'],
    ['Samuel', 'Parks'],
    ['Finnegan', 'Bright'],
    ['Addison', 'Wong'],
    ['Julissa', 'Jennings'],
    ['Sonia', 'Ballard'],
    ['Isabell', 'Scott'],
    ['Edward', 'Ross'],
    ['Triston', 'Sheppard'],
    ['Drake', 'Wallace'],
    ['Fisher', 'Santos'],
    ['Alexis', 'Vargas'],
    ['Malcolm', 'Harvey'],
    ['Omari', 'Christensen'],
    ['Taylor', 'Alvarado'],
    ['Andy', 'Larson'],
    ['Nathan', 'Chapman'],
    ['Arturo', 'Sandoval'],
    ['Brianna', 'Russell'],
    ['Natalya', 'Thompson'],
    ['Daniela', 'Vance'],
    ['Leyla', 'Booth'],
    ['Dangelo', 'Howard'],
    ['Margaret', 'Bowen'],
    ['Anthony', 'Guzman'],
    ['Alyssa', 'Mora'],
    ['Julia', 'Campos'],
    ['Braylon', 'Wong'],
    ['Kailee', 'Kaufman'],
    ['Charlee', 'Whitehead'],
    ['Simone', 'Horne'],
    ['Jaylin', 'Rasmussen'],
    ['Alondra', 'Schneider'],
    ['Kenna', 'Kirk'],
    ['Paul', 'Michael'],
    ['Holly', 'Webster'],
    ['Chad', 'Hensley'],
    ['Princess', 'Small'],
    ['Bryan', 'Clements'],
    ['Zion', 'Hampton'],
    ['Hugh', 'Barron'],
    ['Jordyn', 'Flowers'],
    ['Case', 'Peck'],
    ['Anabella', 'Le'],
    ['Maximilian', 'Mercer'],
    ['Leonidas', 'Joyce'],
    ['Elian', 'Pollard'],
    ['Kristen', 'Cook'],
    ['Caitlyn', 'Hart'],
    ['Georgia', 'Harding'],
    ['Catherine', 'Kane'],
    ['Haiden', 'Obrien'],
    ['Esmeralda', 'Sosa'],
    ['Jimena', 'Nielsen'],
    ['Hillary', 'Andrews'],
    ['Alexis', 'Mccann'],
    ['Heath', 'Monroe'],
    ['Skylar', 'Hines'],
    ['Houston', 'Frost'],
    ['Kane', 'Wood'],
    ['Tessa', 'Macias'],
    ['Aliyah', 'Holden'],
    ['Troy', 'Hurst'],
    ['Peter', 'Bryan'],
    ['Hailey', 'Hinton'],
    ['Shayna', 'Heath'],
    ['Alijah', 'Haas'],
    ['Keegan', 'Delacruz'],
    ['Jazlynn', 'House'],
    ['Amara', 'Anthony'],
    ['Abby', 'Parsons'],
    ['Khloe', 'Foley'],
    ['Aria', 'Sweeney'],
    ['Braylen', 'Knapp'],
    ['Jeramiah', 'Richard'],
    ['Mckenzie', 'Jensen'],
    ['Tanner', 'Ritter'],
    ['Jared', 'Ramirez'],
    ['Derick', 'Sloan'],
    ['Colton', 'Singh'],
    ['Ricardo', 'Franco'],
    ['Harrison', 'Austin'],
    ['Mckenna', 'Burns'],
    ['Baylee', 'Fitzpatrick'],
    ['London', 'Ford'],
    ['Shirley', 'Nelson'],
    ['Rafael', 'Moore'],
    ['Nolan', 'Walters'],
    ['Braedon', 'Melton'],
    ['Kathryn', 'Dillon'],
    ['Eugene', 'Wood'],
    ['Zechariah', 'Ponce'],
    ['Baylee', 'Romero'],
    ['Mckenna', 'Burns'],
    ['Gisselle', 'Bryant'],
]

// Generate Fake Data
for (let i = 1; i <= 100; i++) {
    const div = document.createElement('tr');

    div.setAttribute('tabindex', 0);

    div.innerHTML = `
        <td>${i}</td>
        <td>${names[i][0]}</td>
        <td>${names[i][1]}</td>
        <td>${Math.random() * 100}</td>
    `

    document.querySelector('table tbody').appendChild(div);
}